import java.awt.Component;
import java.awt.Image;
import java.io.*;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class CarRenalSystem {
public class RentalSystemFrame extends javax.swing.JFrame {

    private final CarRental agency;
    ButtonGroup group = new ButtonGroup();

    public RentalSystemFrame() {
        initComponents();
        ImageIcon img = new ImageIcon(new ImageIcon("src/images/cars.png").getImage().getScaledInstance(400, 130, Image.SCALE_SMOOTH));
        imgLbl.setIcon(img);
        group.add(economyRB);
        group.add(vipRB);

        agency = new CarRental(100);
        loadData();

        onExitListener();
    }

    public final boolean loadData() {

        try {
            agency.loadFromFile();
            return true;

        } catch (IOException ex) {

            JOptionPane.showMessageDialog(this, "Error during reading the data\n" + ex, "Car Rental System", JOptionPane.ERROR_MESSAGE);

        } catch (ClassNotFoundException ex) {

            JOptionPane.showMessageDialog(this, "Error during reading the data\n" + ex, "Car Rental System", JOptionPane.ERROR_MESSAGE);

        }
        return false;

    }

    public final void onExitListener() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                int answer = JOptionPane.showConfirmDialog(null, "Do you want to save the applied changes?", "Alert!", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);

                if (answer == JOptionPane.YES_OPTION) {

                    try {

                        ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("cars.dat"));

                        oos.writeInt(agency.getNumOfCars());
                        oos.writeObject(agency.getCarlist());

                        JOptionPane.showMessageDialog(null, "Thank you for using Car Rental System\nAll changes is saved!", "Thank you!",
                                JOptionPane.INFORMATION_MESSAGE);

                    } catch (FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(null, "Error during saving the data", "Car Rental System", JOptionPane.ERROR_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Error during saving the data", "Car Rental System", JOptionPane.ERROR_MESSAGE);
                    }

                } else {

                    JOptionPane.showMessageDialog(null, "Thank you for using Car Rental System\nAll changes NOT saved!", "Thank you !",
                            JOptionPane.INFORMATION_MESSAGE);
                }
                System.exit(0);

            }
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newCarPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        plateNoTxtf = new javax.swing.JTextField();
        pricePerDayTxtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modelTxtf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        colorTxtf = new javax.swing.JTextField();
        vipRB = new javax.swing.JRadioButton();
        economyRB = new javax.swing.JRadioButton();
        driverPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        driverIdTxtf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        driverNameTxtf = new javax.swing.JTextField();
        addCarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        showAllVIPBtn = new javax.swing.JButton();
        showAllEconomyBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        imgLbl = new javax.swing.JLabel();
        rentPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        rentCarPateNoTxtf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        noOfDaysTxtf = new javax.swing.JTextField();
        customerPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cusNameTxtf = new javax.swing.JTextField();
        cusIdTxtf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cusPhoneTxtf = new javax.swing.JTextField();
        rentBtn = new javax.swing.JButton();
        returnCarPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        returnCarPlateNoTxtf = new javax.swing.JTextField();
        returnCarBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rental System");
        setMinimumSize(new java.awt.Dimension(1040, 720));
        setPreferredSize(new java.awt.Dimension(1040, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1040, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newCarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Add New Car"));
        newCarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("plateNo:");
        newCarPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));
        newCarPanel.add(plateNoTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 120, -1));
        newCarPanel.add(pricePerDayTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 120, -1));

        jLabel3.setText("pricePerDay:");
        newCarPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        jLabel4.setText("model:");
        newCarPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, -1));
        newCarPanel.add(modelTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, -1));

        jLabel5.setText("color:");
        newCarPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, -1));
        newCarPanel.add(colorTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 120, -1));

        vipRB.setText("VIP");
        vipRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vipRBActionPerformed(evt);
            }
        });
        newCarPanel.add(vipRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        economyRB.setSelected(true);
        economyRB.setText("Economy");
        economyRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economyRBActionPerformed(evt);
            }
        });
        newCarPanel.add(economyRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        driverPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Driver"));
        driverPanel.setEnabled(false);
        driverPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("id:");
        jLabel6.setEnabled(false);
        driverPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 29, -1, -1));

        driverIdTxtf.setEnabled(false);
        driverPanel.add(driverIdTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 24, 100, -1));

        jLabel7.setText("name:");
        jLabel7.setEnabled(false);
        driverPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, -1, -1));

        driverNameTxtf.setEnabled(false);
        driverNameTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverNameTxtfActionPerformed(evt);
            }
        });
        driverPanel.add(driverNameTxtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 56, 100, -1));

        newCarPanel.add(driverPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 260, 100));

        addCarBtn.setText("Add new car");
        addCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarBtnActionPerformed(evt);
            }
        });
        newCarPanel.add(addCarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        getContentPane().add(newCarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 500, 370));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("CAR RENTAL SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 300, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Show Information"));

        showAllVIPBtn.setText("show all available VIP");
        showAllVIPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllVIPBtnActionPerformed(evt);
            }
        });

        showAllEconomyBtn.setText("show all available Economy");
        showAllEconomyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllEconomyBtnActionPerformed(evt);
            }
        });

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(showAllEconomyBtn)
                        .addGap(33, 33, 33)
                        .addComponent(showAllVIPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAllVIPBtn)
                    .addComponent(showAllEconomyBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 500, 290));

        imgLbl.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(imgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 430, 130));

        rentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Rent Car"));

        jLabel9.setText("plateNo:");

        jLabel10.setText("No. of days:");

        customerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("customer information"));

        jLabel11.setText("id:");

        jLabel12.setText("name:");

        jLabel13.setText("phone:");

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cusIdTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cusNameTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cusPhoneTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cusIdTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cusNameTxtf)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cusPhoneTxtf)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rentBtn.setText("Rent");
        rentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rentPanelLayout = new javax.swing.GroupLayout(rentPanel);
        rentPanel.setLayout(rentPanelLayout);
        rentPanelLayout.setHorizontalGroup(
            rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(rentPanelLayout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(rentCarPateNoTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(rentPanelLayout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(noOfDaysTxtf))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rentPanelLayout.createSequentialGroup()
                    .addGap(165, 165, 165)
                    .addComponent(rentBtn)
                    .addContainerGap(188, Short.MAX_VALUE)))
        );
        rentPanelLayout.setVerticalGroup(
            rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rentCarPateNoTxtf)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noOfDaysTxtf)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(rentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentPanelLayout.createSequentialGroup()
                    .addContainerGap(271, Short.MAX_VALUE)
                    .addComponent(rentBtn)
                    .addContainerGap()))
        );

        getContentPane().add(rentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 440, 330));

        returnCarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Return Car"));

        jLabel14.setText("PlateNo:");

        returnCarBtn.setText("Return car");
        returnCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnCarPanelLayout = new javax.swing.GroupLayout(returnCarPanel);
        returnCarPanel.setLayout(returnCarPanelLayout);
        returnCarPanelLayout.setHorizontalGroup(
            returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnCarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnCarPlateNoTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnCarPanelLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(returnCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        returnCarPanelLayout.setVerticalGroup(
            returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnCarPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnCarPlateNoTxtf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returnCarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(returnCarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 440, 110));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel17.setText("CSC113 Course Simple Project 2020 KSU");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel18.setText("For education purposes only.");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel19.setText("Developed By ENG.NAIF ALSHEHRI@VisionAcademy");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, 380, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void driverNameTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverNameTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverNameTxtfActionPerformed

    private void vipRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vipRBActionPerformed

        hideDriverPanel(true);

    }//GEN-LAST:event_vipRBActionPerformed

    private void economyRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economyRBActionPerformed

        hideDriverPanel(false);

    }//GEN-LAST:event_economyRBActionPerformed

    private void addCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarBtnActionPerformed

        String plateNo, model, color;
        double pricePerDay;
        boolean isAdded;

        //validate fields        
        if (!isFilled(plateNoTxtf, "Plate No")) {
            return;
        }

        plateNo = plateNoTxtf.getText().trim();

        if (!isFilled(pricePerDayTxtf, "Price Per Day")) {
            return;
        }

        if (!isNumber(pricePerDayTxtf, "Price Per Day")) {
            return;

        }
        pricePerDay = getNumericValue(pricePerDayTxtf);

        if (!isAcceptedValue(pricePerDay, "Price Per Day", 0)) {
            return;

        }

        if (!isFilled(modelTxtf, "Model")) {
            return;
        }
        model = modelTxtf.getText().trim();

        if (!isFilled(colorTxtf, "Color")) {
            return;
        }

        color = colorTxtf.getText().trim();

        if (vipRB.isSelected()) {
            if (!isFilled(driverIdTxtf, "Driver Id")) {
                return;
            }

            if (!isNumber(driverIdTxtf, "Driver Id")) {
                return;

            }

            if (!isFilled(driverNameTxtf, "Driver Name")) {
                return;
            }

            int driverId = (int) getNumericValue(driverIdTxtf);

            String driverName = driverNameTxtf.getText().trim();

            isAdded = agency.addCar(new VIP(plateNo, pricePerDay, model, color, new Driver(driverId, driverName)));
        } else {

            isAdded = agency.addCar(new Economy(plateNo, pricePerDay, model, color));

        }

        if (isAdded) {
            JOptionPane.showMessageDialog(this, "A new car has been added successfully!", "New Car",
                    JOptionPane.INFORMATION_MESSAGE);
            //reset fields
            clearPanelTextFields(newCarPanel);
            clearPanelTextFields(driverPanel);

        } else {

            JOptionPane.showMessageDialog(this, "Couldn't add the car\nCar already added or the fleet is full!", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_addCarBtnActionPerformed

    private void showAllEconomyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllEconomyBtnActionPerformed
        textArea.setText("");
        Economy[] cars = agency.searchAvailableEconomy();
        if (cars == null) {
            textArea.append("\nNo economy cars are available!");
            textArea.append("\n-------------------------------------------------------");

        } else {
            for (Economy car : cars) {
                textArea.append("\n" + car.toString());
                textArea.append("\n-------------------------------------------------------");
            }
        }
    }//GEN-LAST:event_showAllEconomyBtnActionPerformed

    private void showAllVIPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllVIPBtnActionPerformed

        textArea.setText("");
        VIP[] cars = agency.searchAvailableVIP();
        if (cars == null) {
            textArea.append("\nNo VIP cars are available!");
            textArea.append("\n-------------------------------------------------------");

        } else {
            for (VIP car : cars) {
                textArea.append("\n" + car.toString());
                textArea.append("\n-------------------------------------------------------");
            }
        }

    }//GEN-LAST:event_showAllVIPBtnActionPerformed

    private void rentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentBtnActionPerformed

        String plateNo, cusName;
        int days, cusId;
        long phone;
        //validate fields        
        if (!isFilled(rentCarPateNoTxtf, "Plate No")) {
            return;
        }

        plateNo = rentCarPateNoTxtf.getText().trim();

        if (!isFilled(noOfDaysTxtf, "Days")) {
            return;
        }

        if (!isNumber(noOfDaysTxtf, "Days")) {
            return;

        }
        days = (int) getNumericValue(noOfDaysTxtf);

        if (!isAcceptedValue(days, "days", 1)) {
            return;

        }

        if (!isFilled(cusIdTxtf, "Customer Id")) {
            return;
        }

        if (!isNumber(cusIdTxtf, "Customer Id")) {
            return;

        }
        cusId = (int) getNumericValue(cusIdTxtf);

        if (!isFilled(cusNameTxtf, "Customer Name")) {
            return;
        }
        cusName = cusNameTxtf.getText().trim();

        if (!isFilled(cusPhoneTxtf, "Phone")) {
            return;
        }

        if (!isNumber(cusPhoneTxtf, "Phone")) {
            return;

        }
        phone = (long) getNumericValue(cusPhoneTxtf);

        Customer customer = new Customer(cusId, cusName, phone);
        String data = agency.rentCar(plateNo, customer, days);

        if (data == null) {

            JOptionPane.showMessageDialog(this, "Could't rent the car!\nThe plate no is invalid\nor the car is not available", "Error",
                    JOptionPane.ERROR_MESSAGE);

        } else {

            JOptionPane.showMessageDialog(this, data, "Rent Car",
                    JOptionPane.INFORMATION_MESSAGE);
            //reset fields
            clearPanelTextFields(rentPanel);
            clearPanelTextFields(customerPanel);

            try {
                //concat the customer info to the bill to save 'em
                data += "\n" + customer;
                saveBill(cusName + "_" + cusId + ".txt", data);
            } catch (FileNotFoundException ex) {

                JOptionPane.showMessageDialog(this, ex.toString(), "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_rentBtnActionPerformed

    private void returnCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnCarBtnActionPerformed

        String plateNo;
        //validate fields        
        if (!isFilled(returnCarPlateNoTxtf, "Plate No")) {
            return;
        }
        plateNo = returnCarPlateNoTxtf.getText().trim();

        if (agency.returnCar(plateNo)) {
            JOptionPane.showMessageDialog(this, "The car has been returned successfully!\nThank you!", "Return Car",
                    JOptionPane.INFORMATION_MESSAGE);
            //reset fields
            clearPanelTextFields(returnCarPanel);
        } else {

            JOptionPane.showMessageDialog(this, "Could't return the car!\nThe plate no is invalid\nor the car is already returned", "Error",
                    JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_returnCarBtnActionPerformed

    //enable - disable panel along with its children components
    public void hideDriverPanel(boolean option) {

        Component[] components = driverPanel.getComponents();

        for (Component component : components) {
            component.setEnabled(option);
        }
        driverPanel.setEnabled(option);
    }

    public void clearPanelTextFields(JPanel panel) {

        Component[] components = panel.getComponents();
        for (Component component : components) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
            }
        }
    }

    //checks if a jext field containing a text or not 
    private boolean isFilled(JTextField field, String fieldName) {

        if (field.getText().trim().equals("")) {
            //display an error message
            JOptionPane.showMessageDialog(this, fieldName + " field is required.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            field.requestFocus();
            return false;
        }

        return true;

    }

    //checks if the entered value is a number 
    private boolean isNumber(JTextField field, String fieldName) {
        String numOfItemsStr = field.getText().trim();
        field.requestFocus();
        try {

            Double.parseDouble(numOfItemsStr);//if it's not a valid number will throw en exception

            return true; // everything is ok 
        } catch (NumberFormatException e) {
            //display an error message
            JOptionPane.showMessageDialog(this, "Only Numbers are alowed in " + fieldName + " Field.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;//terminate the process
        }

    }

    //returns a double value from a text field
    private double getNumericValue(JTextField field) {
        field.requestFocus();
        return Double.parseDouble(field.getText().trim());
    }

    //validates a range of values.
    private boolean isAcceptedValue(double value, String fieldName, int min) {

        if (value < min) {
            //display an error message
            JOptionPane.showMessageDialog(this, "The vlaue of " + fieldName + " field can't be less than " + min, "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;

    }

    public void saveBill(String fileName, String data) throws FileNotFoundException {

        //for text files, use PrintWriter 
        PrintWriter writer = new PrintWriter(new FileOutputStream(new File(fileName)));
        writer.println(data);
        //close the stream
        writer.close();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalSystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalSystemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarBtn;
    private javax.swing.JTextField colorTxtf;
    private javax.swing.JTextField cusIdTxtf;
    private javax.swing.JTextField cusNameTxtf;
    private javax.swing.JTextField cusPhoneTxtf;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JTextField driverIdTxtf;
    private javax.swing.JTextField driverNameTxtf;
    private javax.swing.JPanel driverPanel;
    private javax.swing.JRadioButton economyRB;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modelTxtf;
    private javax.swing.JPanel newCarPanel;
    private javax.swing.JTextField noOfDaysTxtf;
    private javax.swing.JTextField plateNoTxtf;
    private javax.swing.JTextField pricePerDayTxtf;
    private javax.swing.JButton rentBtn;
    private javax.swing.JTextField rentCarPateNoTxtf;
    private javax.swing.JPanel rentPanel;
    private javax.swing.JButton returnCarBtn;
    private javax.swing.JPanel returnCarPanel;
    private javax.swing.JTextField returnCarPlateNoTxtf;
    private javax.swing.JButton showAllEconomyBtn;
    private javax.swing.JButton showAllVIPBtn;
    private javax.swing.JTextArea textArea;
    private javax.swing.JRadioButton vipRB;
    // End of variables declaration//GEN-END:variables
}

}
